version: '3'
services:
  database:
    platform: linux/x86_64
    build: 
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: cases123
      MYSQL_DATABASE: case_studies
      MYSQL_USER: db_user
      MYSQL_PASSWORD: cases123
  webapp:
    platform: linux/x86_64
    depends_on:
      - database
    build: 
      context: ./webapp
      dockerfile: Dockerfile    
    ports:
      - "80:80"
    